name: Test MS SQL server
on:
  pull_request:
  push:

env:
  dbtype: 'sqlsrv'

jobs:
  MSSQLTest:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            moodle: 'MOODLE_404_STABLE'
            experimental: false

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Setting up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          ini-values: 'max_input_vars=5000'

      - name: Install MS SQL server driver
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          source ~/.bashrc
          sudo apt-get install -y unixodbc-dev

      - name: Checkout moodle/moodle
        uses: actions/checkout@v4
        with:
          repository: moodle/moodle
          ref: ${{ matrix.moodle }}

      - name: Setup moodle
        run: |
          echo "pathtophp=$(which php)" >> $GITHUB_ENV # Inject installed pathtophp to env. The template config needs it.
          cp $GITHUB_WORKSPACE/.github/workflows/config-template.php $GITHUB_WORKSPACE/config.php
          mkdir $GITHUB_WORKSPACE/../moodledata
          sudo locale-gen en_AU.UTF-8
          php $GITHUB_WORKSPACE/admin/tool/phpunit/cli/init.php --no-composer-self-update

      - name: Running PHPUnit tests
        run: $GITHUB_WORKSPACE/vendor/bin/phpunit -c $GITHUB_WORKSPACE/phpunit.xml --testsuite=local_testmssql_testsuite --testdox -v
